# Generated by Django 4.0.6 on 2022-08-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_img', models.ImageField(upload_to='slider_img/')),
                ('s_title', models.CharField(max_length=200, verbose_name='Название')),
                ('s_css', models.CharField(default='-', max_length=200, null=True, verbose_name='css класс')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
