# Generated by Django 4.0.6 on 2022-09-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_mycourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourses',
            options={'verbose_name': 'Купленный курс', 'verbose_name_plural': 'Купленные курсы'},
        ),
    ]
