# Generated by Django 4.0.6 on 2022-09-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_mycourses_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='image_desc',
            field=models.TextField(blank=True, verbose_name='Описание картинки'),
        ),
    ]
