# Generated by Django 4.0.6 on 2022-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_allcourses_image_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='tg_url',
            field=models.URLField(default='#', max_length=300, verbose_name='Курс в телеграмм'),
        ),
    ]
