# Generated by Django 4.0.6 on 2022-09-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_allcourses_tg_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sslider',
            name='s_title',
        ),
    ]
