# Generated by Django 4.0.6 on 2022-09-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_sslider_s_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='tg_url',
            field=models.CharField(default='#', max_length=300, verbose_name='Курс в телеграмм'),
        ),
    ]
